use_frameworks!

platform :ios, '12.0'

target 'MaskedTextField_Example' do
  pod 'SwiftMaskedTextField', :path => '../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MaskedTextField_Tests' do
    inherit! :search_paths
  end
end
