use_frameworks!

platform :ios, '9.0'

target 'MaskedTextField_Example' do
  pod 'MaskedTextField', :path => '../'
  pod 'SnapKit'
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'MaskedTextField_Tests' do
    inherit! :search_paths

    
  end
end
